/**
 * Enum values as the API declares them, not as a sample happened to contain them.
 *
 * Source: https://health.googleapis.com/$discovery/rest?version=v4, fetched 2026-09-03.
 *
 * The discovery document is the only place these are published in full. The RPC reference at
 * developers.google.com truncates before the enum definitions, and the workouts page lists four
 * values prefixed by "such as", which reads like a list and is not one. Health Connect publishes a
 * different vocabulary (EXERCISE_TYPE_RUNNING, EXERCISE_TYPE_STRENGTH_TRAINING) that must not be
 * substituted for this one.
 *
 * These exist to make drift detectable: `scripts/check-enum-drift.mjs` diffs them against the live
 * document. Nothing switches on them, so a value the API adds is a reported difference rather than
 * a broken build.
 */
export const EXERCISE_TYPES: readonly string[] = [
  'EXERCISE_TYPE_UNSPECIFIED', 'AEROBIC_WORKOUT', 'ARCHERY', 'ASSAULT_BIKE', 'BACKPACKING',
  'BADMINTON', 'BALLET', 'BALLROOM_DANCE', 'BARRE_CLASS', 'BASEBALL', 'BASKETBALL', 'BIKING',
  'BILLIARDS', 'BODY_WEIGHT', 'BOOTCAMP', 'BOWLING', 'BOXING', 'BREAKDANCING', 'CALISTHENICS',
  'CANOEING', 'CARDIO_SCULPT', 'CARDIO_WORKOUT', 'CARPENTRY', 'CHEERLEADING', 'CIRCUIT_TRAINING',
  'CLEANING', 'CLIMBING', 'CORE_TRAINING', 'CRICKET', 'CROQUET', 'CROSS_COUNTRY_SKI',
  'CROSS_TRAINING', 'CROSSFIT', 'CURLING', 'DANCING', 'DIVING', 'ELECTRIC_BIKE', 'ELECTRIC_SCOOTER',
  'ELLIPTICAL', 'EQUESTRIAN_SPORTS', 'EXERCISE_CLASS', 'FENCING', 'FIELD_HOCKEY', 'FISHING',
  'FITNESS_GAMING', 'FOILING', 'FOOTBALL_AMERICAN', 'FOOTBALL_AUSTRALIAN', 'FREE_WEIGHTS',
  'FRISBEE_PLAYING_GENERAL', 'FUNCTIONAL_STRENGTH_TRAINING', 'GARDENING', 'GOLF', 'GYMNASTICS',
  'HANDBALL', 'HAND_CYCLING', 'HIIT', 'HIKING', 'HIP_HOP', 'HOCKEY', 'HOEING', 'HOUSEHOLD_CHORES',
  'HUNTING', 'ICE_SKATING', 'INCLINE_RUN', 'INCLINE_WALK', 'INDOOR_CLIMBING', 'INTERVAL_WORKOUT',
  'JAZZ_DANCE', 'JIU_JITSU', 'JUMPING_ROPE', 'KARATE', 'KAYAKING', 'KICKBOXING', 'KITESURFING',
  'LACROSSE', 'MARTIAL_ARTS', 'MEDITATE', 'MODERN_DANCE', 'MOTOCROSS', 'MOTORCYCLE', 'MOUNTAIN_BIKE',
  'MOWING_LAWN', 'MUAY_THAI', 'MULTISPORT', 'MUSICAL_PERFORMANCE', 'NORDIC_WALKING', 'ORIENTEERING',
  'OTHER', 'OUTDOOR_BIKE', 'OUTDOOR_WORKOUT', 'PADDLEBOARDING', 'PADEL', 'PAINTING', 'PARAGLIDING',
  'PARKOUR', 'PICKELBALL', 'PILATES', 'POLO', 'POWERLIFTING', 'POWER_WALKING', 'RACKET_SPORTS',
  'RACQUETBALL', 'RESISTANCE_BANDS', 'ROCK_CLIMBING', 'ROLLERBLADING', 'ROLLER_SKATING', 'ROWING',
  'ROWING_MACHINE', 'RUCKING', 'RUGBY', 'RUNNING', 'SAILING', 'SCOOTERING', 'SCUBA_DIVING',
  'SHOOTING', 'SHOVELING', 'SKATEBOARDING', 'SKATING', 'SKIING', 'SKYDIVING', 'SNORKELING',
  'SNOWBOARDING', 'SNOWMOBILING', 'SNOWSHOEING', 'SNOW_SPORT', 'SOCCER', 'SOFTBALL', 'SPEED_SKATING',
  'SPINNING', 'SPORT', 'SQUASH', 'STAIRCLIMBER', 'STATIONARY_BIKE', 'STEP_TRAINING',
  'STRENGTH_TRAINING', 'STRETCHING', 'STROLLER_WALK', 'SURFING', 'SWIMMING', 'SWIMMING_OPEN_WATER',
  'SWIMMING_POOL', 'SYNCHRONIZED_SWIMMING', 'TABATA_WORKOUT', 'TABLE_TENNIS', 'TAEKWONDO', 'TAI_CHI',
  'TANGO', 'TENNIS', 'TRACK_AND_FIELD', 'TRAIL_RUN', 'TRAMPOLINE', 'TREADMILL', 'TREADMILL_WALK',
  'TRX', 'ULTIMATE_FRISBEE', 'UNICYCLING', 'VOLLEYBALL', 'VOLLEYBALL_BEACH', 'WAKEBOARDING',
  'WALKING', 'WALK_WITH_WEIGHTS', 'WATER_AEROBICS', 'WATER_JOGGING', 'WATER_POLO', 'WATER_SKIING',
  'WATER_SPORT', 'WATER_VOLLEYBALL', 'WEEDING', 'WEIGHTLIFTING', 'WEIGHT_MACHINES', 'WEIGHTS',
  'WHEELCHAIR', 'WINDSURFING', 'WORKOUT', 'WRESTLING', 'YOGA', 'YOGA_BIKRAM', 'YOGA_HATHA',
  'YOGA_POWER', 'YOGA_VINYASA', 'ZUMBA',
]

/**
 * The sleep stage vocabulary. ASLEEP and RESTLESS are the classic, non-staged model; the M0 probe
 * recorded only the other four and the derivation discarded these two until M3f-E.
 */
export const SLEEP_STAGE_TYPES: readonly string[] = [
  'AWAKE', 'DEEP', 'LIGHT', 'REM', 'ASLEEP', 'RESTLESS',
]
