import { lookup, resolveSemantic, type SemanticToken, type Theme } from './semantic.js'
import type { ColorPath } from './primitives.js'

/**
 * The Android target: the same palette as the dashboard, emitted as Android resources instead of
 * custom properties.
 *
 * A surface written in another language gets its own emitted target from this package rather than
 * a copied palette, and the companion app is the second surface. The app's layouts name a
  * resource, each resource is a token, and no colour in `res/` is written by hand.
 *
 * The resource names are the token's own, with the dash spelled as an underscore. That is the
 * whole mapping a reader has to hold: `@color/text_secondary` is `text-secondary` in
 * `semantic.ts`, in both themes at once, and a token that moved would move here with it rather
 * than leaving a second vocabulary behind.
 */
const FROM_SEMANTIC = {
  surface_page: 'surface-page',
  surface_card: 'surface-card',
  surface_inset: 'surface-inset',
  border_subtle: 'border-subtle',
  text_primary: 'text-primary',
  text_secondary: 'text-secondary',
  text_muted: 'text-muted',
  accent: 'accent',
  accent_soft: 'accent-soft',
  // What a chosen row and a primary button paint on: both themes answer blue.950 and blue.50 for
  // `surface-selected` and `surface-accent`, so one resource serves both without a second name.
  surface_selected: 'surface-selected',
  negative: 'negative',
  positive: 'positive',
} satisfies Record<string, SemanticToken>

/**
 * The one colour with no semantic token behind it, and the reason it has none.
 *
 * A screen has three states and the semantic layer names two of them: `negative` and `positive`.
 * The web paints the third, the sync's amber bar, with the negative tone instead, so there is no
 * shared token to read. `amber` is where both themes' own answer already lives, and the chart's
 * own `stage-awake` reads exactly these two steps, so this reuses them rather than minting a
  * token the dashboard would not use.
 */
const FROM_PRIMITIVE = {
  warning: { dark: 'amber.500', light: 'amber.700' },
} satisfies Record<string, Record<Theme, ColorPath>>

export type AndroidColorName = keyof typeof FROM_SEMANTIC | keyof typeof FROM_PRIMITIVE

export const ANDROID_COLOR_NAMES: AndroidColorName[] = [
  ...Object.keys(FROM_SEMANTIC),
  ...Object.keys(FROM_PRIMITIVE),
] as AndroidColorName[]

/** Every colour the app reads, resolved for one theme. */
export function resolveAndroidColors(theme: Theme): Record<AndroidColorName, string> {
  const semantic = resolveSemantic(theme)
  return Object.fromEntries([
    ...Object.entries(FROM_SEMANTIC).map(([name, token]) => [name, semantic[token]]),
    ...Object.entries(FROM_PRIMITIVE).map(([name, path]) => [name, lookup(path[theme])]),
  ]) as Record<AndroidColorName, string>
}

export function emitAndroidColors(theme: Theme): string {
  const colors = resolveAndroidColors(theme)
  const lines = ANDROID_COLOR_NAMES.map((name) => `    <color name="${name}">${colors[name]}</color>`)
  return (
    '<?xml version="1.0" encoding="utf-8"?>\n' +
    '<!-- generated by @haelan/tokens, do not edit by hand -->\n' +
    `<resources>\n${lines.join('\n')}\n</resources>\n`
  )
}

/**
 * The two files at the paths Android reads them from.
 *
 * `values` is the default palette and `values-night` the dark one, which is the platform's own
 * convention rather than a choice: it is what makes the app follow the phone's setting the way the
 * stylesheet follows `prefers-color-scheme`, instead of picking one theme and staying in it.
 */
export function androidColorFiles(): Array<{ path: string, xml: string }> {
  return [
    { path: 'values/colors.xml', xml: emitAndroidColors('light') },
    { path: 'values-night/colors.xml', xml: emitAndroidColors('dark') },
  ]
}
