import { primitives } from './primitives.js'
import { resolveSemantic } from './semantic.js'
import { resolveChart } from './chart.js'

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((l) => `  ${l}`).join('\n')}\n}\n`
}

function scales(): string[] {
  return [
    ...Object.entries(primitives.space).map(([k, v]) => `--space-${k}: ${v};`),
    ...Object.entries(primitives.radius).map(([k, v]) => `--radius-${k}: ${v};`),
    ...Object.entries(primitives.text).map(([k, v]) => `--font-size-${k}: ${v};`),
    `--font-sans: ${primitives.font.sans};`,
    `--font-mono: ${primitives.font.mono};`,
  ]
}

function themeLines(theme: 'dark' | 'light'): string[] {
  return [
    ...Object.entries(resolveSemantic(theme)).map(([k, v]) => `--${k}: ${v};`),
    ...Object.entries(resolveChart(theme)).map(([k, v]) => `--chart-${k}: ${v};`),
  ]
}

export function emitCss(): string {
  return (
    '/* generated by @vitals/tokens, do not edit by hand */\n' +
    block(':root', [...scales(), ...themeLines('dark')]) +
    block("[data-theme='light']", themeLines('light'))
  )
}
