import { primitives } from './primitives.js'
import { resolveSemantic, SEMANTIC_KEYS, type SemanticToken } from './semantic.js'
import { resolveChart, CHART_KEYS, type ChartToken } from './chart.js'

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((l) => `  ${l}`).join('\n')}\n}\n`
}

// The single authority for custom-property names: importing these instead of retyping catches a rename as a compile error.
export function semanticVar(token: SemanticToken): string {
  return `--${token}`
}

export function chartVar(token: ChartToken): string {
  return `--chart-${token}`
}

export function themeVarNames(): string[] {
  return [...SEMANTIC_KEYS.map(semanticVar), ...CHART_KEYS.map(chartVar)]
}

function scales(): string[] {
  return [
    ...Object.entries(primitives.space).map(([k, v]) => `--space-${k}: ${v};`),
    ...Object.entries(primitives.radius).map(([k, v]) => `--radius-${k}: ${v};`),
    ...Object.entries(primitives.text).map(([k, v]) => `--font-size-${k}: ${v};`),
    `--font-sans: ${primitives.font.sans};`,
    `--font-mono: ${primitives.font.mono};`,
  ]
}

function themeLines(theme: 'dark' | 'light'): string[] {
  const s = resolveSemantic(theme)
  const c = resolveChart(theme)
  return [
    ...SEMANTIC_KEYS.map((k) => `${semanticVar(k)}: ${s[k]};`),
    ...CHART_KEYS.map((k) => `${chartVar(k)}: ${c[k]};`),
  ]
}

export function emitCss(): string {
  return (
    '/* generated by @vitals/tokens, do not edit by hand */\n' +
    block(':root', [...scales(), ...themeLines('dark')]) +
    block("[data-theme='light']", themeLines('light'))
  )
}
