import { primitives } from './primitives.js'
import { resolveSemantic, SEMANTIC_KEYS, type SemanticToken } from './semantic.js'
import { resolveChart, CHART_KEYS, type ChartToken } from './chart.js'

function block(selector: string, lines: string[], indent = ''): string {
  return `${indent}${selector} {\n${lines.map((l) => `${indent}  ${l}`).join('\n')}\n${indent}}\n`
}

// The single authority for custom-property names: importing these instead of retyping catches a rename as a compile error.
export function semanticVar(token: SemanticToken): string {
  return `--${token}`
}

export function chartVar(token: ChartToken): string {
  return `--chart-${token}`
}

export function themeVarNames(): string[] {
  return [...SEMANTIC_KEYS.map(semanticVar), ...CHART_KEYS.map(chartVar)]
}

function scales(): string[] {
  return [
    ...Object.entries(primitives.space).map(([k, v]) => `--space-${k}: ${v};`),
    ...Object.entries(primitives.radius).map(([k, v]) => `--radius-${k}: ${v};`),
    ...Object.entries(primitives.text).map(([k, v]) => `--font-size-${k}: ${v};`),
    `--font-sans: ${primitives.font.sans};`,
    `--font-mono: ${primitives.font.mono};`,
    ...Object.entries(primitives.duration).map(([k, v]) => `--duration-${k}: ${v};`),
    ...Object.entries(primitives.ease).map(([k, v]) => `--ease-${k}: ${v};`),
  ]
}

function themeLines(theme: 'dark' | 'light'): string[] {
  const s = resolveSemantic(theme)
  const c = resolveChart(theme)
  return [
    ...SEMANTIC_KEYS.map((k) => `${semanticVar(k)}: ${s[k]};`),
    ...CHART_KEYS.map((k) => `${chartVar(k)}: ${c[k]};`),
  ]
}

export function emitCss(): string {
  const light = themeLines('light')
  return (
    '/* generated by @haelan/tokens, do not edit by hand */\n' +
    // Dark is the reference theme and the fallback: a reader whose system says nothing, and any
    // agent that ignores media queries entirely, still gets a complete and coherent palette.
    // color-scheme rides with the palette in all three blocks below, because a native control
    // takes its chrome from this property and from nothing else we set. Without it Firefox drew
    // the source picker's option list with default light chrome under our light-on-dark text, so
    // the options were near white on white and unreadable. It has to track the theme everywhere
    // the palette does: set it once on :root only, and the popup would go dark for a reader whose
    // system asked for light.
    block(':root', [...scales(), ...themeLines('dark'), 'color-scheme: dark;']) +
    // What the reader's own system asks for, when the reader has not overruled it. The :not
    // guard is what makes the override work in both directions - without it, choosing dark on a
    // light-mode machine would be silently undone here.
    '@media (prefers-color-scheme: light) {\n' +
    block(":root:not([data-theme='dark'])", [...light, 'color-scheme: light;'], '  ') +
    '}\n' +
    // The explicit choice, which has to sit outside the media query or it could never win on a
    // dark-mode machine.
    block("[data-theme='light']", [...light, 'color-scheme: light;']) +
    // Zero rather than absent, so a rule reading the variable still resolves. ECharts is handled
    // separately in charts/base.ts; this covers CSS transitions.
    '@media (prefers-reduced-motion: reduce) {\n' +
    block(':root', ['--duration-fast: 0ms;', '--duration-slow: 0ms;'], '  ') +
    '}\n'
  )
}
