import { describe, it, expect } from 'vitest'
import { ANDROID_COLOR_NAMES, androidColorFiles, emitAndroidColors, resolveAndroidColors } from '../src/android.js'
import { resolveSemantic } from '../src/semantic.js'
import { resolveChart } from '../src/chart.js'
import { primitives } from '../src/primitives.js'

describe('android emitter', () => {
  const files = androidColorFiles()
  const light = files.find((f) => f.path === 'values/colors.xml')!.xml
  const dark = files.find((f) => f.path === 'values-night/colors.xml')!.xml

  it('emits the two files Android reads a day and a night palette from', () => {
    expect(files.map((f) => f.path)).toEqual(['values/colors.xml', 'values-night/colors.xml'])
  })

  // A colour present in values and missing from values-night does not fail anything: the device
  // silently keeps the day value in the dark theme, which is the failure this pins.
  it('defines every colour in both files', () => {
    for (const name of ANDROID_COLOR_NAMES) {
      expect(light, `${name} missing from values`).toContain(`<color name="${name}">`)
      expect(dark, `${name} missing from values-night`).toContain(`<color name="${name}">`)
    }
  })

  // AAPT rejects a resource name with a dash, and the token vocabulary is full of them, so the
  // translation is asserted rather than assumed.
  it('spells every resource name the way aapt accepts it', () => {
    for (const name of ANDROID_COLOR_NAMES) {
      expect(name, `${name} is not a valid Android resource name`).toMatch(/^[a-z][a-z0-9_]*$/)
    }
  })

  it('reads the semantic layer rather than repeating its values', () => {
    const semantic = resolveSemantic('light')
    expect(light).toContain(`<color name="surface_card">${semantic['surface-card']}</color>`)
    expect(light).toContain(`<color name="text_secondary">${semantic['text-secondary']}</color>`)
    expect(light).toContain(`<color name="surface_selected">${semantic['surface-selected']}</color>`)
    expect(light).toContain(`<color name="negative">${semantic.negative}</color>`)
    // The night file reads the same layer for the other theme, which is what makes one definition
    // serve both.
    expect(dark).toContain(`<color name="surface_card">${resolveSemantic('dark')['surface-card']}</color>`)
  })

  it('gives the two themes different values, so one file cannot be standing in for the other', () => {
    expect(light).not.toEqual(dark)
    expect(resolveAndroidColors('light').surface_card).not.toEqual(resolveAndroidColors('dark').surface_card)
    expect(emitAndroidColors('light')).toContain(primitives.slate[100])
    expect(emitAndroidColors('dark')).toContain(primitives.slate[900])
  })

  it('takes the warning state from amber, which is where both themes answer it', () => {
    expect(light).toContain(`<color name="warning">${primitives.amber[700]}</color>`)
    expect(dark).toContain(`<color name="warning">${primitives.amber[500]}</color>`)
  })

  it('records that the file is generated', () => {
    expect(light.startsWith('<?xml version="1.0" encoding="utf-8"?>')).toBe(true)
    expect(light).toContain('generated by @haelan/tokens, do not edit by hand')
    expect(dark).toContain('generated by @haelan/tokens, do not edit by hand')
  })

  // The sleep-stage and chart colours, resolved from the same map the web's `--chart-*` custom
  // properties come from (chart.ts, via emit.ts's chartVar), never a hex literal copied by eye.
  // border-chosen and text-faint are semantic tokens rather than chart ones, but the dashboard
  // reads both from the same chart card (the gauge band arc, and its faint label), so this app
  // reads them the same way.
  it('gives the chart its stage, series and scale colours from the same map the web reads', () => {
    const chartLight = resolveChart('light')
    const chartDark = resolveChart('dark')
    const semanticLight = resolveSemantic('light')
    const semanticDark = resolveSemantic('dark')

    expect(light).toContain(`<color name="stage_deep">${chartLight['stage-deep']}</color>`)
    expect(light).toContain(`<color name="stage_light">${chartLight['stage-light']}</color>`)
    expect(light).toContain(`<color name="stage_rem">${chartLight['stage-rem']}</color>`)
    expect(light).toContain(`<color name="stage_awake">${chartLight['stage-awake']}</color>`)
    expect(light).toContain(`<color name="chart_series">${chartLight.series}</color>`)
    expect(light).toContain(`<color name="chart_series_alt">${chartLight['series-alt']}</color>`)
    expect(light).toContain(`<color name="chart_band">${chartLight['band-baseline']}</color>`)
    expect(light).toContain(`<color name="chart_scale_4">${chartLight['scale-4']}</color>`)
    expect(light).toContain(`<color name="chart_grid">${chartLight.grid}</color>`)
    expect(light).toContain(`<color name="border_chosen">${semanticLight['border-chosen']}</color>`)
    expect(light).toContain(`<color name="text_faint">${semanticLight['text-faint']}</color>`)

    expect(dark).toContain(`<color name="stage_deep">${chartDark['stage-deep']}</color>`)
    expect(dark).toContain(`<color name="stage_light">${chartDark['stage-light']}</color>`)
    expect(dark).toContain(`<color name="stage_rem">${chartDark['stage-rem']}</color>`)
    expect(dark).toContain(`<color name="stage_awake">${chartDark['stage-awake']}</color>`)
    expect(dark).toContain(`<color name="chart_series">${chartDark.series}</color>`)
    expect(dark).toContain(`<color name="chart_series_alt">${chartDark['series-alt']}</color>`)
    expect(dark).toContain(`<color name="chart_band">${chartDark['band-baseline']}</color>`)
    expect(dark).toContain(`<color name="chart_scale_4">${chartDark['scale-4']}</color>`)
    expect(dark).toContain(`<color name="chart_grid">${chartDark.grid}</color>`)
    expect(dark).toContain(`<color name="border_chosen">${semanticDark['border-chosen']}</color>`)
    expect(dark).toContain(`<color name="text_faint">${semanticDark['text-faint']}</color>`)
  })
})
