import { describe, it, expect } from 'vitest'
import { emitCss, themeVarNames, semanticVar, chartVar } from '../src/emit.js'
import { resolveSemantic } from '../src/semantic.js'
import { resolveChart } from '../src/chart.js'

describe('css emitter', () => {
  const css = emitCss()

  it('defines dark values on :root', () => {
    expect(css).toMatch(/:root\s*\{/)
    expect(css).toContain(`${semanticVar('surface-card')}: ${resolveSemantic('dark')['surface-card']};`)
    expect(css).toContain(`${chartVar('stage-deep')}: ${resolveChart('dark')['stage-deep']};`)
  })

  it('overrides only the semantic and chart layers for the light theme', () => {
    expect(css).toMatch(/\[data-theme='light'\]\s*\{/)
    const light = css.slice(css.indexOf("[data-theme='light']"))
    expect(light).toContain(`${semanticVar('surface-card')}: ${resolveSemantic('light')['surface-card']};`)
    expect(light).not.toContain('--space-4:')
  })

  // The light theme was fully built and fully tested and nothing could reach it: dark sat on
  // bare :root, there was no prefers-color-scheme block, and index.html hardcoded the attribute.
  // A theme that exists only in the test suite is not a theme that ships.
  it('follows the system preference when the reader has not chosen a theme', () => {
    expect(css).toMatch(/@media \(prefers-color-scheme: light\)/)
    const media = css.slice(css.indexOf('@media (prefers-color-scheme: light)'))
    expect(media).toContain(`${semanticVar('surface-card')}: ${resolveSemantic('light')['surface-card']};`)
  })

  // Both directions, which is the part that is easy to get half right: a light-mode system with
  // dark chosen has to stay dark, and a dark-mode system with light chosen has to go light.
  it('lets an explicit choice beat the system preference in both directions', () => {
    const media = css.slice(css.indexOf('@media (prefers-color-scheme: light)'))
    expect(media, 'the system light rule must exclude an explicit dark choice')
      .toContain(":root:not([data-theme='dark'])")
    expect(css, 'an explicit light choice needs a rule of its own, outside the media query')
      .toContain("[data-theme='light'] {")
  })

  it('emits spacing and type scales once, outside the theme blocks', () => {
    expect(css).toContain('--space-4: 16px;')
    expect(css).toContain('--font-size-xl: 34px;')
    expect(css).toContain('--font-size-micro: 12px;')
  })

  it('defines every theme custom property in both themes', () => {
    const dark = css.slice(css.indexOf(':root'), css.indexOf("[data-theme='light']"))
    const light = css.slice(css.indexOf("[data-theme='light']"))
    for (const name of themeVarNames()) {
      expect(dark, `${name} missing from :root`).toContain(`${name}: `)
      expect(light, `${name} missing from the light theme`).toContain(`${name}: `)
    }
  })

  it('records that the file is generated', () => {
    expect(css.startsWith('/* generated by @haelan/tokens')).toBe(true)
  })

  it('emits the motion scale and honours a reduced-motion preference', () => {
    expect(css).toContain('--duration-fast: 120ms;')
    expect(css).toContain('--ease-standard:')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
    // Zero rather than absent: a rule that reads var(--duration-fast) must still resolve.
    expect(css).toMatch(/@media \(prefers-reduced-motion: reduce\) \{[\s\S]*--duration-fast: 0ms;/)
  })

  // The landing page wrote page-level rhythm as calc(var(--space-6) * 2), and arithmetic on a
  // token is the tell that the scale is short. These three are where that rhythm actually sits.
  it('carries the spacing scale up to the page-level steps', () => {
    expect(css).toContain('--space-7: 32px;')
    expect(css).toContain('--space-8: 48px;')
    expect(css).toContain('--space-9: 64px;')
  })
})
