import { describe, it, expect } from 'vitest'
import { emitCss } from '../src/emit.js'

describe('css emitter', () => {
  const css = emitCss()

  it('defines dark values on :root', () => {
    expect(css).toMatch(/:root\s*\{/)
    expect(css).toContain('--surface-card: #121926;')
    expect(css).toContain('--chart-stage-deep: #3730A3;')
  })

  it('overrides only the semantic layer for the light theme', () => {
    expect(css).toMatch(/\[data-theme='light'\]\s*\{/)
    expect(css).toContain('--surface-card: #FFFFFF;')
  })

  it('emits spacing and type scales', () => {
    expect(css).toContain('--space-4: 16px;')
    expect(css).toContain('--font-size-xl: 26px;')
  })

  it('records that the file is generated', () => {
    expect(css.startsWith('/* generated by @vitals/tokens')).toBe(true)
  })
})
