export { openDatabase, closeDatabase, tableExists, DATABASE_FILENAME } from './db/open.ts'
export type { Database } from './db/open.ts'
export { migrateToLatest } from './db/migrate.ts'
export * as schema from './db/schema/index.ts'
export { loadOrCreateKey, KEY_FILENAME, KEY_ENV_VAR } from './crypto/key.ts'
export { seal, unseal } from './crypto/secretBox.ts'
export { CredentialStore } from './store/credentials.ts'
export type { ClientCredentials, StoredRefreshToken } from './store/credentials.ts'
export { RawArchive } from './store/rawArchive.ts'
export type { PutInput, PutResult } from './store/rawArchive.ts'
export { createTestDatabase, seedPerson } from './testing/fixtures.ts'
export type { TestDatabase } from './testing/fixtures.ts'
export { DATA_TYPES, dataTypeById, FILTER_MEMBERS } from './api/catalogue.ts'
export type { DataType, FilterMember, MappingTarget } from './api/catalogue.ts'
export { TokenProvider, RevokedError } from './api/tokens.ts'
export type { TokenProviderDeps } from './api/tokens.ts'
export { HealthClient } from './api/client.ts'
export type { ListInput, ListResult, ClientDeps } from './api/client.ts'
export { mapSamples } from './api/mapSamples.ts'
export type { SampleRow } from './api/mapSamples.ts'
export { mapSessions } from './api/mapSessions.ts'
export type { SessionRow, SegmentRow } from './api/mapSessions.ts'
