import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const dir = new URL('./samples/', import.meta.url)
const summary = JSON.parse(readFileSync(new URL('_summary.json', dir), 'utf8'))

// Enum domains are schema, not health data, and M1's mapper cannot be written without them.
// Anything not on this list contributes its type and nothing else. Device display names are
// excluded deliberately: they are user chosen and identify a household member's hardware.
const ENUMS = new Set([
  'type', 'stagesStatus', 'recordingMethod', 'platform', 'exerciseType', 'splitType',
  'calculationMethod', 'formFactor', 'userProvidedUnit', 'unit', 'source', 'status',
])

const shape = (node, prefix, acc) => {
  if (Array.isArray(node)) {
    acc.set(prefix + '[]', { type: 'array', n: (acc.get(prefix + '[]')?.n ?? 0) + node.length })
    for (const item of node.slice(0, 40)) shape(item, prefix + '[]', acc)
    return
  }
  if (node && typeof node === 'object') {
    for (const [k, v] of Object.entries(node)) shape(v, prefix ? `${prefix}.${k}` : k, acc)
    return
  }
  const leaf = prefix.split('.').pop()
  const rec = acc.get(prefix) ?? { type: typeof node, values: new Set() }
  rec.type = typeof node
  if (ENUMS.has(leaf) && rec.values.size < 12 && typeof node === 'string') rec.values.add(node)
  acc.set(prefix, rec)
}

let md = `# v4 field map, observed ${new Date().toISOString().slice(0, 10)}\n\n`
md += `Generated by probe/field-map.mjs from archived payloads. Paths and types only. Values\n`
md += `appear only for enum-like schema fields, never for a measurement, a timestamp or a\n`
md += `device name. This file is the input to M1's table driven mapping module.\n\n`
md += `## Filter members\n\nOne data type wears three casings: kebab in the URL path, snake in the filter, camel in the\n`
md += `response body. The filterable member differs by type and is not documented.\n\n`
md += `| Type | List | Filter member | Points | kB | Page cap hit |\n|---|---|---|---|---|---|\n`
for (const r of summary) {
  md += `| \`${r.type}\` | ${r.list ? 'yes' : 'no'} | ${r.list ? '`' + r.filter + '`' : r.supports} | ${r.points ?? ''} | ${r.kb ?? ''} | ${r.truncated ? 'yes' : ''} |\n`
}

md += `\n## Fields by type\n`
for (const file of readdirSync(dir).filter((f) => !f.startsWith('_')).sort()) {
  const json = JSON.parse(readFileSync(new URL(file, dir), 'utf8'))
  const points = json.dataPoints ?? []
  const type = file.replace(/\.json$/, '')
  md += `\n### ${type}\n\n`
  if (!points.length) { md += `No data points in any window probed.\n`; continue }
  const acc = new Map()
  for (const p of points.slice(0, 200)) shape(p, '', acc)
  md += '```\n'
  for (const [path, rec] of [...acc].sort((a, b) => a[0].localeCompare(b[0]))) {
    const vals = rec.values && rec.values.size ? `  {${[...rec.values].sort().join(' | ')}}` : ''
    md += `${path.padEnd(52)} ${rec.type}${vals}\n`
  }
  md += '```\n'
  md += `\nPoints in the archived window: ${points.length}.\n`
}

writeFileSync(new URL('./findings/field-map.md', import.meta.url), md)
console.log('wrote probe/findings/field-map.md')
