package com.haelan.android.glance.format

// The web's glance sentences, copied from apps/web/src/i18n/{en,nl}.json under the resource names
// GlanceWords asks for (the key path in snake case), so a test asserts the sentence a reader of the
// web reads. The same text goes into values/strings.xml and values-nl/strings.xml, and
// GlanceStringResourcesTest holds the two files to it. The activity_ keys at the end are the
// Activity list's own row words, which the Today card's workout rows print as SessionRow does.

internal val ENGLISH_TEXT: Map<String, String> = mapOf(
    "recovery_units_breaths_per_minute_short" to "breaths/min",
    "activity_units_min" to "min",
    "charts_absence_not_staged" to "This night was not staged, so there is nothing to total.",
    "charts_units_percent" to "%",
    "sleep_stage_deep" to "Deep",
    "sleep_stage_light" to "Light",
    "sleep_stage_rem" to "REM",
    "sleep_stage_awake" to "Awake",
    "recovery_index_band_low" to "Well below your usual",
    "recovery_index_band_below" to "Below your usual",
    "recovery_index_band_usual" to "Around your usual",
    "recovery_index_band_above" to "Above your usual",
    "recovery_index_band_high" to "Well above your usual",
    "glance_span" to "last night, and today until {{time}}",
    "glance_span_no_time" to "last night, and today so far",
    "glance_span_no_night" to "no night recorded · today until {{time}}",
    "glance_span_no_night_no_time" to "no night recorded · today so far",
    "glance_greeting_morning" to "Good morning",
    "glance_greeting_afternoon" to "Good afternoon",
    "glance_greeting_evening" to "Good evening",
    "glance_usual_within" to "within your usual {{low}} – {{high}}",
    "glance_usual_above" to "above your usual {{low}} – {{high}}",
    "glance_usual_below" to "below your usual {{low}} – {{high}}",
    "glance_usual_thin" to "not enough history for a usual yet",
    "glance_usual_partial" to "so far; your usual day {{center}}",
    "glance_as_of_time" to "as of {{time}}",
    "glance_as_of_today" to "today",
    "glance_as_of_yesterday" to "yesterday",
    "glance_as_of_night" to "night of {{date}}",
    "glance_as_of_that_day" to "that day",
    "glance_as_of_day_before" to "the day before",
    "glance_no_reading" to "No reading yet",
    "glance_no_reading_finished" to "No reading",
    "glance_pace_ahead" to "Ahead of your usual pace",
    "glance_pace_on" to "On your usual pace",
    "glance_pace_behind" to "Behind your usual pace",
    "glance_pace_usual_by" to "usual by {{time}} is {{value}}",
    "glance_sleep_title" to "Last night",
    "glance_sleep_asleep" to "Time asleep",
    "glance_sleep_efficiency" to "Efficiency",
    "glance_sleep_bed" to "Bed",
    "glance_sleep_woke" to "Woke",
    "glance_sleep_strip" to "Time asleep, last 7 nights",
    "glance_sleep_strip_finished" to "Time asleep, the 7 nights up to that day",
    "glance_sleep_caption" to "last 7 nights",
    "glance_sleep_caption_finished" to "the 7 nights up to that day",
    "glance_sleep_link" to "View this night",
    "glance_sleep_efficiency_standing_above" to "higher than usual",
    "glance_sleep_efficiency_standing_below" to "lower than usual",
    "glance_sleep_bed_standing_above" to "later than usual",
    "glance_sleep_bed_standing_below" to "earlier than usual",
    "glance_sleep_woke_standing_above" to "later than usual",
    "glance_sleep_woke_standing_below" to "earlier than usual",
    "glance_sleep_title_finished" to "That night",
    "glance_recovery_title" to "Recovery",
    "glance_recovery_index" to "Recovery index",
    "glance_recovery_rhr" to "Resting HR",
    "glance_recovery_hrv" to "HRV",
    "glance_recovery_respiratory" to "Breathing rate {{value}}, above your usual",
    "glance_recovery_unscored" to "Not enough readings to score yet.",
    "glance_recovery_unscored_finished" to "Not enough readings to score.",
    "glance_recovery_not_scored" to "Not scored",
    "glance_recovery_score" to "Score",
    "glance_recovery_score_unscored" to "Score, not scored",
    "glance_recovery_strip" to "Recovery index, last 7 days",
    "glance_recovery_strip_finished" to "Recovery index, the 7 days up to that day",
    "glance_recovery_caption" to "last 7 days",
    "glance_recovery_caption_finished" to "the 7 days up to that day",
    "glance_recovery_link" to "View recovery",
    "glance_today_title" to "Today",
    "glance_today_subtitle" to "so far",
    "glance_today_steps" to "Steps",
    "glance_today_active_minutes" to "Active minutes",
    "glance_today_heart_rate_since_midnight" to "Heart rate · 00:00 → now",
    "glance_today_heart_rate_chart" to "Heart rate today",
    "glance_today_strip" to "Steps, last 7 days",
    "glance_today_strip_finished" to "Steps, the 7 days up to that day",
    "glance_today_caption" to "last 7 days",
    "glance_today_caption_finished" to "the 7 days up to that day",
    "glance_today_link" to "View activity",
    "glance_today_that_day" to "That day",
    "glance_today_day_standing_within" to "Within your usual day",
    "glance_today_day_standing_above" to "Above your usual day",
    "glance_today_day_standing_below" to "Below your usual day",
    "glance_today_usual_range" to "usual {{low}} – {{high}}",
    "glance_today_heart_rate_whole_day" to "Heart rate · 00:00 → 24:00",
    "glance_today_heart_rate_chart_that_day" to "Heart rate that day",
    "glance_workouts_title" to "Today's activities",
    "glance_workouts_title_that_day" to "That day's activities",
    "glance_week_title" to "This week",
    "glance_week_title_finished" to "That week",
    "glance_week_subtitle" to "last 7 days",
    "glance_week_subtitle_finished" to "the 7 days up to that day",
    "glance_week_steps" to "Steps",
    "glance_week_active" to "Active",
    "glance_week_asleep" to "Asleep",
    "glance_week_per_day" to "{{value}} a day",
    "glance_week_per_night" to "a night",
    "glance_week_total_per" to "· {{per}}",
    "glance_week_bars_label" to "{{what}}, last 7 days; the average counts finished days only, today not counted",
    "glance_week_bars_label_nights" to "{{what}}, last 7 nights; the average includes last night",
    "glance_week_bars_label_finished" to "{{what}}, the 7 days up to that day; the average counts every day shown",
    "glance_week_bar" to "{{date}}: {{label}} {{value}}",
    "glance_week_open_bar" to "Open {{date}}: {{label}} {{value}}",
    "glance_week_bars_label_nights_finished" to "{{what}}, the 7 nights up to that day; the average includes that night",
    "glance_open_day" to "Open this day",
    "glance_open_day_idle" to "Tap a day to open it",
    "glance_open_day_named" to "Open {{date}}",
    "glance_subtitle_today" to "today",
    "glance_subtitle_yesterday" to "yesterday",
    "glance_subtitle_that_day" to "that day",
    "glance_subtitle_day_before" to "the day before",
    "glance_empty_title" to "Nothing here yet",
    "glance_empty_detail" to "Once a sync brings in a night or a day, it shows up here.",
    "glance_offline" to "Shown from {{time}}, not reachable",
    "glance_too_old" to "This server is too old for the glance; update it to 2.13.0 or later",
    "shell_error_title" to "This instance did not answer.",
    "shell_error_detail" to "It may be restarting or temporarily unreachable. Try again in a moment.",
    "shell_error_retry" to "Try again",
    "glance_day_nav_label" to "Day",
    "glance_day_nav_previous" to "Previous day",
    "glance_day_nav_next" to "Next day",
    "glance_day_nav_today" to "Today",
    "glance_day_nav_calendar" to "Pick a date",
    "glance_day_nav_past_line" to "that night, and the whole day",
    "glance_day_nav_past_line_no_night" to "no night recorded · the whole day",
    "glance_calendar_previous_month" to "Previous month",
    "glance_calendar_next_month" to "Next month",
    "glance_calendar_sleep_legend" to "Sleep",
    "glance_calendar_sleep_within" to "usual",
    "glance_calendar_sleep_outside" to "unusual",
    "glance_calendar_steps_legend" to "Steps",
    "glance_calendar_steps_reached" to "reached",
    "glance_calendar_steps_below" to "not reached",
    "glance_calendar_grey_days" to "Grey: no data",
    "glance_calendar_today" to "Today",
    "glance_calendar_day" to "{{date}}, {{sleep}}, {{steps}}",
    "glance_calendar_no_data" to "{{date}}, no data",
    "glance_calendar_spoken_sleep_within" to "slept in your usual range",
    "glance_calendar_spoken_sleep_outside" to "slept outside your usual range",
    "glance_calendar_spoken_sleep_none" to "sleep not judged",
    "glance_calendar_spoken_steps_reached" to "steps reached your usual",
    "glance_calendar_spoken_steps_below" to "steps below your usual",
    "glance_calendar_spoken_steps_none" to "steps not judged",
    "charts_units_bpm" to "bpm",
    "charts_units_milliseconds" to "ms",
    "activity_units_km" to "km",
    "activity_units_kcal_short" to "kcal",
    "activity_units_bpm" to "bpm",
    "activity_units_pace_suffix" to "/km",
    "activity_units_elevation_gain_short" to "m gained",
    "activity_sessions_excluded" to "Excluded: {{reason}}",
    "activity_sessions_excluded_no_reason" to "Excluded",
    "activity_exercise_types_walking" to "Walking",
    "activity_exercise_types_cardio_workout" to "Cardio workout",
    "activity_exercise_types_running" to "Running",
    "activity_exercise_types_workout" to "Workout",
    "activity_exercise_types_spinning" to "Spinning",
    "activity_exercise_types_biking" to "Biking",
    "activity_exercise_types_treadmill" to "Treadmill",
    "activity_exercise_types_hiking" to "Hiking",
    "activity_exercise_types_weightlifting" to "Weightlifting",
    "activity_exercise_types_stroller_walk" to "Stroller walk",
    "activity_exercise_types_swimming_pool" to "Swimming pool",
    "activity_exercise_types_sport" to "Sport",
    "activity_exercise_types_household_chores" to "Household chores",
    "activity_exercise_types_unknown" to "Unknown",
)

internal val DUTCH_TEXT: Map<String, String> = mapOf(
    "recovery_units_breaths_per_minute_short" to "ademh./min",
    "activity_units_min" to "min",
    "charts_absence_not_staged" to "Deze nacht is niet in fasen ingedeeld, dus is er niets te tellen.",
    "charts_units_percent" to "%",
    "sleep_stage_deep" to "Diep",
    "sleep_stage_light" to "Licht",
    "sleep_stage_rem" to "REM",
    "sleep_stage_awake" to "Wakker",
    "recovery_index_band_low" to "Ruim onder gebruikelijk",
    "recovery_index_band_below" to "Onder gebruikelijk",
    "recovery_index_band_usual" to "Zoals gebruikelijk",
    "recovery_index_band_above" to "Boven gebruikelijk",
    "recovery_index_band_high" to "Ruim boven gebruikelijk",
    "glance_span" to "afgelopen nacht, en vandaag tot {{time}}",
    "glance_span_no_time" to "afgelopen nacht, en vandaag tot nu toe",
    "glance_span_no_night" to "afgelopen nacht niet gemeten · vandaag tot {{time}}",
    "glance_span_no_night_no_time" to "afgelopen nacht niet gemeten · vandaag tot nu toe",
    "glance_greeting_morning" to "Goedemorgen",
    "glance_greeting_afternoon" to "Goedemiddag",
    "glance_greeting_evening" to "Goedenavond",
    "glance_usual_within" to "binnen je gebruikelijke bereik {{low}} – {{high}}",
    "glance_usual_above" to "boven je gebruikelijke bereik {{low}} – {{high}}",
    "glance_usual_below" to "onder je gebruikelijke bereik {{low}} – {{high}}",
    "glance_usual_thin" to "nog te weinig geschiedenis voor een gebruikelijke waarde",
    "glance_usual_partial" to "tot nu toe; op een gewone dag {{center}}",
    "glance_as_of_time" to "bijgewerkt om {{time}}",
    "glance_as_of_today" to "vandaag",
    "glance_as_of_yesterday" to "gisteren",
    "glance_as_of_night" to "nacht van {{date}}",
    "glance_as_of_that_day" to "die dag",
    "glance_as_of_day_before" to "de dag ervoor",
    "glance_no_reading" to "Nog geen meting",
    "glance_no_reading_finished" to "Geen meting",
    "glance_pace_ahead" to "Vóór op je gebruikelijke tempo",
    "glance_pace_on" to "Op je gebruikelijke tempo",
    "glance_pace_behind" to "Achter op je gebruikelijke tempo",
    "glance_pace_usual_by" to "normaal zit je om {{time}} op {{value}}",
    "glance_sleep_title" to "Afgelopen nacht",
    "glance_sleep_asleep" to "Slaaptijd",
    "glance_sleep_efficiency" to "Efficiëntie",
    "glance_sleep_bed" to "Naar bed",
    "glance_sleep_woke" to "Wakker",
    "glance_sleep_strip" to "Tijd geslapen, laatste 7 nachten",
    "glance_sleep_strip_finished" to "Tijd geslapen, de 7 nachten tot en met die dag",
    "glance_sleep_caption" to "laatste 7 nachten",
    "glance_sleep_caption_finished" to "de 7 nachten tot en met die dag",
    "glance_sleep_link" to "Bekijk deze nacht",
    "glance_sleep_efficiency_standing_above" to "hoger dan gewoonlijk",
    "glance_sleep_efficiency_standing_below" to "lager dan gewoonlijk",
    "glance_sleep_bed_standing_above" to "later dan gewoonlijk",
    "glance_sleep_bed_standing_below" to "eerder dan gewoonlijk",
    "glance_sleep_woke_standing_above" to "later dan gewoonlijk",
    "glance_sleep_woke_standing_below" to "eerder dan gewoonlijk",
    "glance_sleep_title_finished" to "Die nacht",
    "glance_recovery_title" to "Herstel",
    "glance_recovery_index" to "Herstelindex",
    "glance_recovery_rhr" to "Rusthartslag",
    "glance_recovery_hrv" to "HRV",
    "glance_recovery_respiratory" to "Ademhaling {{value}}, boven je gebruikelijke waarde",
    "glance_recovery_unscored" to "Nog niet genoeg metingen om te scoren.",
    "glance_recovery_unscored_finished" to "Niet genoeg metingen om te scoren.",
    "glance_recovery_not_scored" to "Geen score",
    "glance_recovery_score" to "Score",
    "glance_recovery_score_unscored" to "Score, niet gescoord",
    "glance_recovery_strip" to "Herstelindex, laatste 7 dagen",
    "glance_recovery_strip_finished" to "Herstelindex, de 7 dagen tot en met die dag",
    "glance_recovery_caption" to "laatste 7 dagen",
    "glance_recovery_caption_finished" to "de 7 dagen tot en met die dag",
    "glance_recovery_link" to "Bekijk herstel",
    "glance_today_title" to "Vandaag",
    "glance_today_subtitle" to "tot nu toe",
    "glance_today_steps" to "Stappen",
    "glance_today_active_minutes" to "Actieve minuten",
    "glance_today_heart_rate_since_midnight" to "Hartslag · 00:00 → nu",
    "glance_today_heart_rate_chart" to "Hartslag vandaag",
    "glance_today_strip" to "Stappen, laatste 7 dagen",
    "glance_today_strip_finished" to "Stappen, de 7 dagen tot en met die dag",
    "glance_today_caption" to "laatste 7 dagen",
    "glance_today_caption_finished" to "de 7 dagen tot en met die dag",
    "glance_today_link" to "Bekijk activiteit",
    "glance_today_that_day" to "Die dag",
    "glance_today_day_standing_within" to "Zoals op een gewone dag",
    "glance_today_day_standing_above" to "Meer dan op een gewone dag",
    "glance_today_day_standing_below" to "Minder dan op een gewone dag",
    "glance_today_usual_range" to "normaal {{low}} – {{high}}",
    "glance_today_heart_rate_whole_day" to "Hartslag · 00:00 → 24:00",
    "glance_today_heart_rate_chart_that_day" to "Hartslag die dag",
    "glance_workouts_title" to "Activiteiten van vandaag",
    "glance_workouts_title_that_day" to "Activiteiten van die dag",
    "glance_week_title" to "Deze week",
    "glance_week_title_finished" to "Die week",
    "glance_week_subtitle" to "laatste 7 dagen",
    "glance_week_subtitle_finished" to "de 7 dagen tot en met die dag",
    "glance_week_steps" to "Stappen",
    "glance_week_active" to "Actief",
    "glance_week_asleep" to "Slaaptijd",
    "glance_week_per_day" to "{{value}} per dag",
    "glance_week_per_night" to "per nacht",
    "glance_week_total_per" to "· {{per}}",
    "glance_week_bars_label" to "{{what}}, laatste 7 dagen; het gemiddelde telt alleen hele dagen mee, vandaag dus nog niet",
    "glance_week_bars_label_nights" to "{{what}}, laatste 7 nachten; afgelopen nacht telt mee in het gemiddelde",
    "glance_week_bars_label_finished" to "{{what}}, de 7 dagen tot en met die dag; het gemiddelde telt elke getoonde dag mee",
    "glance_week_bar" to "{{date}}: {{label}} {{value}}",
    "glance_week_open_bar" to "Open {{date}}: {{label}} {{value}}",
    "glance_week_bars_label_nights_finished" to "{{what}}, de 7 nachten tot en met die dag; die nacht telt mee in het gemiddelde",
    "glance_open_day" to "Open deze dag",
    "glance_open_day_idle" to "Tik op een dag om hem te openen",
    "glance_open_day_named" to "Open {{date}}",
    "glance_subtitle_today" to "vandaag",
    "glance_subtitle_yesterday" to "gisteren",
    "glance_subtitle_that_day" to "die dag",
    "glance_subtitle_day_before" to "de dag ervoor",
    "glance_empty_title" to "Nog niets te zien",
    "glance_empty_detail" to "Zodra een synchronisatie een nacht of een dag binnenhaalt, verschijnt die hier.",
    "glance_offline" to "Weergegeven van {{time}}, niet bereikbaar",
    "glance_too_old" to "Deze server is te oud voor het overzicht; werk hem bij naar 2.13.0 of later",
    "shell_error_title" to "Deze instantie gaf geen antwoord.",
    "shell_error_detail" to "Mogelijk wordt er opnieuw opgestart of is er tijdelijk geen verbinding. Probeer het straks opnieuw.",
    "shell_error_retry" to "Opnieuw proberen",
    "glance_day_nav_label" to "Dag",
    "glance_day_nav_previous" to "Vorige dag",
    "glance_day_nav_next" to "Volgende dag",
    "glance_day_nav_today" to "Vandaag",
    "glance_day_nav_calendar" to "Kies een datum",
    "glance_day_nav_past_line" to "die nacht, en de hele dag",
    "glance_day_nav_past_line_no_night" to "die nacht niet gemeten · de hele dag",
    "glance_calendar_previous_month" to "Vorige maand",
    "glance_calendar_next_month" to "Volgende maand",
    "glance_calendar_sleep_legend" to "Slaap",
    "glance_calendar_sleep_within" to "gewoon",
    "glance_calendar_sleep_outside" to "afwijkend",
    "glance_calendar_steps_legend" to "Stappen",
    "glance_calendar_steps_reached" to "gehaald",
    "glance_calendar_steps_below" to "niet gehaald",
    "glance_calendar_grey_days" to "Grijs: geen gegevens",
    "glance_calendar_today" to "Vandaag",
    "glance_calendar_day" to "{{date}}, {{sleep}}, {{steps}}",
    "glance_calendar_no_data" to "{{date}}, geen gegevens",
    "glance_calendar_spoken_sleep_within" to "binnen je gebruikelijke bereik geslapen",
    "glance_calendar_spoken_sleep_outside" to "buiten je gebruikelijke bereik geslapen",
    "glance_calendar_spoken_sleep_none" to "slaap niet beoordeeld",
    "glance_calendar_spoken_steps_reached" to "je gebruikelijke aantal stappen gehaald",
    "glance_calendar_spoken_steps_below" to "minder stappen dan gewoonlijk",
    "glance_calendar_spoken_steps_none" to "stappen niet beoordeeld",
    "charts_units_bpm" to "bpm",
    "charts_units_milliseconds" to "ms",
    "activity_units_km" to "km",
    "activity_units_kcal_short" to "kcal",
    "activity_units_bpm" to "bpm",
    "activity_units_pace_suffix" to "/km",
    "activity_units_elevation_gain_short" to "m omhoog",
    "activity_sessions_excluded" to "Uitgesloten: {{reason}}",
    "activity_sessions_excluded_no_reason" to "Uitgesloten",
    "activity_exercise_types_walking" to "Wandelen",
    "activity_exercise_types_cardio_workout" to "Cardiotraining",
    "activity_exercise_types_running" to "Hardlopen",
    "activity_exercise_types_workout" to "Work-out",
    "activity_exercise_types_spinning" to "Spinning",
    "activity_exercise_types_biking" to "Fietsen",
    "activity_exercise_types_treadmill" to "Loopband",
    "activity_exercise_types_hiking" to "Hiken",
    "activity_exercise_types_weightlifting" to "Krachttraining",
    "activity_exercise_types_stroller_walk" to "Wandelen met kinderwagen",
    "activity_exercise_types_swimming_pool" to "Baanzwemmen",
    "activity_exercise_types_sport" to "Sport",
    "activity_exercise_types_household_chores" to "Huishoudelijke klussen",
    "activity_exercise_types_unknown" to "Onbekend",
)

/** Strings over one of the maps above, failing loudly on a key the map does not have. */
internal class MapStrings(private val text: Map<String, String>) : Strings {
    override fun get(key: String, args: Map<String, String>): String =
        Strings.fill(checkNotNull(text[key]) { "no text for $key" }, args)
}
