package com.haelan.android.glance.ui

import android.content.res.Resources
import com.haelan.android.R
import com.haelan.android.glance.format.Strings
import java.util.Locale

/**
 * Every key [com.haelan.android.glance.format.GlanceWords] and the cards ask for, and the resource
 * that holds its text. A map rather than `Resources.getIdentifier`: each entry names a generated
 * `R.string` field, so a key whose resource was renamed or dropped fails the build instead of
 * failing a lookup on somebody's phone, and the resource shrinker can see every string is used.
 * GlanceStringResourcesTest checks the other direction, that every sentence the web wrote has an
 * entry here and in both resource files.
 */
internal val GLANCE_STRING_IDS: Map<String, Int> = mapOf(
    "recovery_units_breaths_per_minute_short" to R.string.recovery_units_breaths_per_minute_short,
    "activity_units_min" to R.string.activity_units_min,
    "charts_absence_not_staged" to R.string.charts_absence_not_staged,
    "charts_units_percent" to R.string.charts_units_percent,
    "sleep_stage_deep" to R.string.sleep_stage_deep,
    "sleep_stage_light" to R.string.sleep_stage_light,
    "sleep_stage_rem" to R.string.sleep_stage_rem,
    "sleep_stage_awake" to R.string.sleep_stage_awake,
    "recovery_index_band_low" to R.string.recovery_index_band_low,
    "recovery_index_band_below" to R.string.recovery_index_band_below,
    "recovery_index_band_usual" to R.string.recovery_index_band_usual,
    "recovery_index_band_above" to R.string.recovery_index_band_above,
    "recovery_index_band_high" to R.string.recovery_index_band_high,
    "glance_span" to R.string.glance_span,
    "glance_span_no_time" to R.string.glance_span_no_time,
    "glance_span_no_night" to R.string.glance_span_no_night,
    "glance_span_no_night_no_time" to R.string.glance_span_no_night_no_time,
    "glance_greeting_morning" to R.string.glance_greeting_morning,
    "glance_greeting_afternoon" to R.string.glance_greeting_afternoon,
    "glance_greeting_evening" to R.string.glance_greeting_evening,
    "glance_usual_within" to R.string.glance_usual_within,
    "glance_usual_above" to R.string.glance_usual_above,
    "glance_usual_below" to R.string.glance_usual_below,
    "glance_usual_thin" to R.string.glance_usual_thin,
    "glance_usual_partial" to R.string.glance_usual_partial,
    "glance_as_of_time" to R.string.glance_as_of_time,
    "glance_as_of_today" to R.string.glance_as_of_today,
    "glance_as_of_yesterday" to R.string.glance_as_of_yesterday,
    "glance_as_of_night" to R.string.glance_as_of_night,
    "glance_as_of_that_day" to R.string.glance_as_of_that_day,
    "glance_as_of_day_before" to R.string.glance_as_of_day_before,
    "glance_no_reading" to R.string.glance_no_reading,
    "glance_no_reading_finished" to R.string.glance_no_reading_finished,
    "glance_pace_ahead" to R.string.glance_pace_ahead,
    "glance_pace_on" to R.string.glance_pace_on,
    "glance_pace_behind" to R.string.glance_pace_behind,
    "glance_pace_usual_by" to R.string.glance_pace_usual_by,
    "glance_sleep_title" to R.string.glance_sleep_title,
    "glance_sleep_asleep" to R.string.glance_sleep_asleep,
    "glance_sleep_efficiency" to R.string.glance_sleep_efficiency,
    "glance_sleep_bed" to R.string.glance_sleep_bed,
    "glance_sleep_woke" to R.string.glance_sleep_woke,
    "glance_sleep_strip" to R.string.glance_sleep_strip,
    "glance_sleep_strip_finished" to R.string.glance_sleep_strip_finished,
    "glance_sleep_caption" to R.string.glance_sleep_caption,
    "glance_sleep_caption_finished" to R.string.glance_sleep_caption_finished,
    "glance_sleep_link" to R.string.glance_sleep_link,
    "glance_sleep_efficiency_standing_above" to R.string.glance_sleep_efficiency_standing_above,
    "glance_sleep_efficiency_standing_below" to R.string.glance_sleep_efficiency_standing_below,
    "glance_sleep_bed_standing_above" to R.string.glance_sleep_bed_standing_above,
    "glance_sleep_bed_standing_below" to R.string.glance_sleep_bed_standing_below,
    "glance_sleep_woke_standing_above" to R.string.glance_sleep_woke_standing_above,
    "glance_sleep_woke_standing_below" to R.string.glance_sleep_woke_standing_below,
    "glance_sleep_title_finished" to R.string.glance_sleep_title_finished,
    "glance_recovery_title" to R.string.glance_recovery_title,
    "glance_recovery_index" to R.string.glance_recovery_index,
    "glance_recovery_rhr" to R.string.glance_recovery_rhr,
    "glance_recovery_hrv" to R.string.glance_recovery_hrv,
    "glance_recovery_respiratory" to R.string.glance_recovery_respiratory,
    "glance_recovery_unscored" to R.string.glance_recovery_unscored,
    "glance_recovery_unscored_finished" to R.string.glance_recovery_unscored_finished,
    "glance_recovery_not_scored" to R.string.glance_recovery_not_scored,
    "glance_recovery_score" to R.string.glance_recovery_score,
    "glance_recovery_score_unscored" to R.string.glance_recovery_score_unscored,
    "glance_recovery_strip" to R.string.glance_recovery_strip,
    "glance_recovery_strip_finished" to R.string.glance_recovery_strip_finished,
    "glance_recovery_caption" to R.string.glance_recovery_caption,
    "glance_recovery_caption_finished" to R.string.glance_recovery_caption_finished,
    "glance_recovery_link" to R.string.glance_recovery_link,
    "glance_today_title" to R.string.glance_today_title,
    "glance_today_subtitle" to R.string.glance_today_subtitle,
    "glance_today_steps" to R.string.glance_today_steps,
    "glance_today_active_minutes" to R.string.glance_today_active_minutes,
    "glance_today_heart_rate_since_midnight" to R.string.glance_today_heart_rate_since_midnight,
    "glance_today_heart_rate_chart" to R.string.glance_today_heart_rate_chart,
    "glance_today_strip" to R.string.glance_today_strip,
    "glance_today_strip_finished" to R.string.glance_today_strip_finished,
    "glance_today_caption" to R.string.glance_today_caption,
    "glance_today_caption_finished" to R.string.glance_today_caption_finished,
    "glance_today_link" to R.string.glance_today_link,
    "glance_today_that_day" to R.string.glance_today_that_day,
    "glance_today_day_standing_within" to R.string.glance_today_day_standing_within,
    "glance_today_day_standing_above" to R.string.glance_today_day_standing_above,
    "glance_today_day_standing_below" to R.string.glance_today_day_standing_below,
    "glance_today_usual_range" to R.string.glance_today_usual_range,
    "glance_today_heart_rate_whole_day" to R.string.glance_today_heart_rate_whole_day,
    "glance_today_heart_rate_chart_that_day" to R.string.glance_today_heart_rate_chart_that_day,
    "glance_workouts_title" to R.string.glance_workouts_title,
    "glance_workouts_title_that_day" to R.string.glance_workouts_title_that_day,
    "glance_week_title" to R.string.glance_week_title,
    "glance_week_title_finished" to R.string.glance_week_title_finished,
    "glance_week_subtitle" to R.string.glance_week_subtitle,
    "glance_week_subtitle_finished" to R.string.glance_week_subtitle_finished,
    "glance_week_steps" to R.string.glance_week_steps,
    "glance_week_active" to R.string.glance_week_active,
    "glance_week_asleep" to R.string.glance_week_asleep,
    "glance_week_per_day" to R.string.glance_week_per_day,
    "glance_week_per_night" to R.string.glance_week_per_night,
    "glance_week_total_per" to R.string.glance_week_total_per,
    "glance_week_bars_label" to R.string.glance_week_bars_label,
    "glance_week_bars_label_nights" to R.string.glance_week_bars_label_nights,
    "glance_week_bars_label_finished" to R.string.glance_week_bars_label_finished,
    "glance_week_bar" to R.string.glance_week_bar,
    "glance_week_open_bar" to R.string.glance_week_open_bar,
    "glance_week_bars_label_nights_finished" to R.string.glance_week_bars_label_nights_finished,
    "glance_open_day" to R.string.glance_open_day,
    "glance_open_day_idle" to R.string.glance_open_day_idle,
    "glance_open_day_named" to R.string.glance_open_day_named,
    "glance_subtitle_today" to R.string.glance_subtitle_today,
    "glance_subtitle_yesterday" to R.string.glance_subtitle_yesterday,
    "glance_subtitle_that_day" to R.string.glance_subtitle_that_day,
    "glance_subtitle_day_before" to R.string.glance_subtitle_day_before,
    "glance_empty_title" to R.string.glance_empty_title,
    "glance_empty_detail" to R.string.glance_empty_detail,
    "glance_offline" to R.string.glance_offline,
    "glance_offline_day" to R.string.glance_offline_day,
    "glance_too_old" to R.string.glance_too_old,
    "shell_error_title" to R.string.shell_error_title,
    "shell_error_detail" to R.string.shell_error_detail,
    "shell_error_retry" to R.string.shell_error_retry,
    "glance_day_nav_label" to R.string.glance_day_nav_label,
    "glance_day_nav_previous" to R.string.glance_day_nav_previous,
    "glance_day_nav_next" to R.string.glance_day_nav_next,
    "glance_day_nav_today" to R.string.glance_day_nav_today,
    "glance_day_nav_calendar" to R.string.glance_day_nav_calendar,
    "glance_day_nav_past_line" to R.string.glance_day_nav_past_line,
    "glance_day_nav_past_line_no_night" to R.string.glance_day_nav_past_line_no_night,
    "glance_calendar_previous_month" to R.string.glance_calendar_previous_month,
    "glance_calendar_next_month" to R.string.glance_calendar_next_month,
    "glance_calendar_sleep_legend" to R.string.glance_calendar_sleep_legend,
    "glance_calendar_sleep_within" to R.string.glance_calendar_sleep_within,
    "glance_calendar_sleep_outside" to R.string.glance_calendar_sleep_outside,
    "glance_calendar_steps_legend" to R.string.glance_calendar_steps_legend,
    "glance_calendar_steps_reached" to R.string.glance_calendar_steps_reached,
    "glance_calendar_steps_below" to R.string.glance_calendar_steps_below,
    "glance_calendar_grey_days" to R.string.glance_calendar_grey_days,
    "glance_calendar_today" to R.string.glance_calendar_today,
    "glance_calendar_day" to R.string.glance_calendar_day,
    "glance_calendar_no_data" to R.string.glance_calendar_no_data,
    "glance_calendar_spoken_sleep_within" to R.string.glance_calendar_spoken_sleep_within,
    "glance_calendar_spoken_sleep_outside" to R.string.glance_calendar_spoken_sleep_outside,
    "glance_calendar_spoken_sleep_none" to R.string.glance_calendar_spoken_sleep_none,
    "glance_calendar_spoken_steps_reached" to R.string.glance_calendar_spoken_steps_reached,
    "glance_calendar_spoken_steps_below" to R.string.glance_calendar_spoken_steps_below,
    "glance_calendar_spoken_steps_none" to R.string.glance_calendar_spoken_steps_none,
    "charts_units_bpm" to R.string.charts_units_bpm,
    "charts_units_milliseconds" to R.string.charts_units_milliseconds,
    "activity_units_km" to R.string.activity_units_km,
    "activity_units_kcal_short" to R.string.activity_units_kcal_short,
    "activity_units_bpm" to R.string.activity_units_bpm,
    "activity_units_pace_suffix" to R.string.activity_units_pace_suffix,
    "activity_units_elevation_gain_short" to R.string.activity_units_elevation_gain_short,
    "activity_sessions_excluded" to R.string.activity_sessions_excluded,
    "activity_sessions_excluded_no_reason" to R.string.activity_sessions_excluded_no_reason,
    "activity_exercise_types_walking" to R.string.activity_exercise_types_walking,
    "activity_exercise_types_cardio_workout" to R.string.activity_exercise_types_cardio_workout,
    "activity_exercise_types_running" to R.string.activity_exercise_types_running,
    "activity_exercise_types_workout" to R.string.activity_exercise_types_workout,
    "activity_exercise_types_spinning" to R.string.activity_exercise_types_spinning,
    "activity_exercise_types_biking" to R.string.activity_exercise_types_biking,
    "activity_exercise_types_treadmill" to R.string.activity_exercise_types_treadmill,
    "activity_exercise_types_hiking" to R.string.activity_exercise_types_hiking,
    "activity_exercise_types_weightlifting" to R.string.activity_exercise_types_weightlifting,
    "activity_exercise_types_stroller_walk" to R.string.activity_exercise_types_stroller_walk,
    "activity_exercise_types_swimming_pool" to R.string.activity_exercise_types_swimming_pool,
    "activity_exercise_types_sport" to R.string.activity_exercise_types_sport,
    "activity_exercise_types_household_chores" to R.string.activity_exercise_types_household_chores,
    "activity_exercise_types_unknown" to R.string.activity_exercise_types_unknown,
    "log_panel_open" to R.string.log_panel_open,
    "log_panel_title_today" to R.string.log_panel_title_today,
    "log_panel_title_yesterday" to R.string.log_panel_title_yesterday,
    "log_panel_title_day" to R.string.log_panel_title_day,
    "log_panel_previous_day" to R.string.log_panel_previous_day,
    "log_panel_next_day" to R.string.log_panel_next_day,
    "log_panel_mood_label" to R.string.log_panel_mood_label,
    "log_panel_mood_1" to R.string.log_panel_mood_1,
    "log_panel_mood_2" to R.string.log_panel_mood_2,
    "log_panel_mood_3" to R.string.log_panel_mood_3,
    "log_panel_mood_4" to R.string.log_panel_mood_4,
    "log_panel_mood_5" to R.string.log_panel_mood_5,
    "log_panel_chips_label" to R.string.log_panel_chips_label,
    "log_panel_chips_count_today" to R.string.log_panel_chips_count_today,
    "log_panel_chips_count_day" to R.string.log_panel_chips_count_day,
    "log_panel_chips_edit" to R.string.log_panel_chips_edit,
    "log_panel_edit_remove" to R.string.log_panel_edit_remove,
    "log_panel_edit_add" to R.string.log_panel_edit_add,
    "log_panel_edit_add_button" to R.string.log_panel_edit_add_button,
    "log_panel_edit_moved" to R.string.log_panel_edit_moved,
    "log_panel_edit_done" to R.string.log_panel_edit_done,
    "log_panel_edit_cancel" to R.string.log_panel_edit_cancel,
    "log_panel_edit_full" to R.string.log_panel_edit_full,
    "log_panel_edit_duplicate" to R.string.log_panel_edit_duplicate,
    "log_panel_undo_today" to R.string.log_panel_undo_today,
    "log_panel_undo_day" to R.string.log_panel_undo_day,
    "log_panel_undo_action" to R.string.log_panel_undo_action,
    "log_panel_note_label" to R.string.log_panel_note_label,
    "log_panel_note_placeholder" to R.string.log_panel_note_placeholder,
    "annotate_event_kinds_illness" to R.string.annotate_event_kinds_illness,
    "annotate_event_kinds_travel" to R.string.annotate_event_kinds_travel,
    "annotate_event_kinds_alcohol" to R.string.annotate_event_kinds_alcohol,
    "annotate_event_kinds_medication" to R.string.annotate_event_kinds_medication,
    "annotate_event_kinds_injury" to R.string.annotate_event_kinds_injury,
    "annotate_event_kinds_caffeine" to R.string.annotate_event_kinds_caffeine,
    "control_row_close" to R.string.control_row_close,
    "log_panel_edit_move_earlier" to R.string.log_panel_edit_move_earlier,
    "log_panel_edit_move_later" to R.string.log_panel_edit_move_later,
    "glance_account_open" to R.string.glance_account_open,
)

/**
 * [Strings] over the app's resources: the key's text in the phone's language (Dutch or English,
 * the two the app ships), its `{{name}}` placeholders filled by [Strings.fill]. A key missing from
 * [GLANCE_STRING_IDS] is a programming error, and fails as one rather than printing the key.
 */
internal class ResourceStrings(private val resources: Resources) : Strings {
    override fun get(key: String, args: Map<String, String>): String {
        val id = checkNotNull(GLANCE_STRING_IDS[key]) { "no string resource for $key" }
        return Strings.fill(resources.getString(id), args)
    }
}

/**
 * The locale numbers and dates are written in, from [resolved], the `glance_locale` string as the
 * resources resolved it: Dutch when the sentences are Dutch, otherwise English, because English is
 * the text the resources fall back to. A German phone reads the English sentences, and "1.827
 * steps" inside one would be a German number in an English sentence.
 *
 * Read from the resources rather than the phone's first locale: a phone set to German then Dutch
 * resolves the resources to values-nl, and its first locale would have written English numbers
 * and dates into Dutch sentences.
 */
internal fun glanceLocale(resolved: String): Locale = if (resolved == "nl") DUTCH else Locale.ENGLISH

private val DUTCH: Locale = Locale.forLanguageTag("nl-NL")
